#SPDX-License-Identifier: MIT-0
---
# tasks file for httpd
- name: "Installing Apache"
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
- name: "Confirm Apache Installation"
  ansible.builtin.command:
    cmd: systemctl status apache2
    